### ISSUE TITLE
USB不识别

### ISSUE THREAD

**Issue by XiaoDong99** [xl120022/ASUS-B85PG-E3-RX570-MAC10.15#2]
同款主板，安装后后置只有两个USB2.0被识别，前面板和后置USB3.0均识别不了，不知道哪里问题

**Comment by xl120022** [comment]
我的正常，但是前置USB我得是坏得&nbsp; &nbsp;没法测试，你可以自己重新定制
。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xl120022/ASUS-B85PG-E3-RX570-MAC10.15"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月17日(星期五) 中午1:47
收件人:&nbsp;"xl120022/ASUS-B85PG-E3-RX570-MAC10.15"<ASUS-B85PG-E3-RX570-MAC10.15@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xl120022/ASUS-B85PG-E3-RX570-MAC10.15] USB不识别 (#2)





 
同款主板，安装后后置只有两个USB2.0被识别，前面板和后置USB3.0均识别不了，不知道哪里问题

**Comment by xl120022** [comment]
重新放入usb驱动，重新订制------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;XiaoDong99&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月8日(星期六) 上午10:25
收件人:&nbsp;&quot;xl120022/ASUS-B85PG-E3-RX570-MAC10.15&quot;<ASUS-B85PG-E3-RX570-MAC10.15@noreply.github.com&gt;;
抄送:&nbsp;&quot;xl120022&quot;<2727574633@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xl120022/ASUS-B85PG-E3-RX570-MAC10.15] USB不识别 (#2)
